// Rooms
export const REQUEST_ROOMS_PENDING = 'REQUEST_ROOMS_PENDING';
export const REQUEST_ROOMS_SUCCESS = 'REQUEST_ROOMS_SUCCESS';
export const REQUEST_ROOMS_FAILED = 'REQUEST_ROOMS_FAILED';
export const SET_ROOM = 'SET_ROOM';
export const ADD_ROOM = 'ADD_ROOM';
export const RECEIVE_ROOM = 'RECEIVE_ROOM';

// Messages
export const REQUEST_MESSAGES_PENDING = 'REQUEST_MESSAGES_PENDING';
export const REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS';
export const REQUEST_MESSAGES_FAILED = 'REQUEST_MESSAGES_FAILED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const UPLOAD_PENDING = 'UPLOAD_PENDING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';

// User Info
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGOUT = 'LOGOUT'