export const REQUEST_ROOMS_PENDING = 'REQUEST_ROOMS_PENDING';
export const REQUEST_ROOMS_SUCCESS = 'REQUEST_ROOMS_SUCCESS';
export const REQUEST_ROOMS_FAILED = 'REQUEST_ROOMS_FAILED';
export const SET_ROOM = 'SET_ROOM';
export const ADD_ROOM = 'ADD_ROOM';
export const RECEIVE_ROOM = 'RECEIVE_ROOM';